version: "3.9"
services:
  worker:
    build: .
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
    ports:
      - "3000:3000"  
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_ID: ${rQ4hSKzB#oQbdopUyqCgKFBM_pp-Y5M7hKXoxGESlMJ8rvSpxSsQ}
      REMOVEBG_KEY: ${REMOVEBG_KEY}
      PREFIX: ${.}
  redis:
    image: redis
volumes:
  logvolume01: {}
  
